#!/bin/sh
# $RedRiver: MirrorOpenBSD,v 1.4 2007/10/01 20:17:23 andrew Exp $

. /etc/OpenBSDTorrents.conf

cd ${OBT_DIR_HOME}
PIDFILE=${OBT_DIR_HOME}/run/mirror.pid

if [ -e ${PIDFILE} ]; then
	PID=`head -1 ${PIDFILE}`
	kill -0 ${PID} 2> /dev/null
	if [ $? -eq 0 ]; then
		echo Already running
		exit 1
	fi
fi
echo $$ > ${PIDFILE}

lftp -f ${OBT_DIR_HOME}/lftp-OpenBSD.script
