#!/bin/sh
# $RedRiver: MirrorOpenBSD,v 1.3 2007/02/07 23:09:05 andrew Exp $

. /etc/OpenBSDTorrents.conf

cd ${OBT_DIR_HOME}
PIDFILE=${OBT_DIR_HOME}/run/mirror.pid

if [ -e ${PIDFILE} ]; then
	PID=`head -1 ${PIDFILE}`
	kill -0 ${PID} 2> /dev/null
	if [ $? -eq 0 ]; then
		echo Already running
		exit 1
	fi
fi
echo $$ > ${PIDFILE}

SERVER=rsync://openbsd.mirrors.tds.net/OpenBSD
#SERVER=rsync://ftp3.usa.openbsd.org/ftp/

rsync -az \
	--delete --delete-excluded \
	--verbose=1 --log-format="%o \`%f'%L %b %l" \
	-f "exclude .*" \
	-f "exclude ls-lR.gz" \
	-f "exclude /OpenBGPD/" \
	-f "exclude /OpenNTPD/" \
	-f "exclude /OpenSSH/" \
	-f "exclude /cvs/" \
	-f "exclude /src/" \
	-f "exclude /distfiles/" \
	-f "exclude /patches/" \
	-f "exclude /snapshots/packages/" \
	-f "exclude /2\.?/" \
	-f "exclude /3\.?/" \
	${SERVER} ${OBT_DIR_FTP}/${OBT_BASENAME}

